const DATA_URL="data/week4/processed/santa_clara_mammography_tracts.geojson";
const COLORS=["#eff3ff","#c6dbef","#9ecae1","#6baed6","#3182bd","#08519c"];
const formatPct=value=>`${d3.format(".1f")(value)}%`;
let tractData,map;

fetch(DATA_URL).then(response=>{if(!response.ok)throw new Error(`Data request failed (${response.status})`);return response.json()}).then(data=>{
  if(data.type!=="FeatureCollection"||!data.features.length)throw new Error("The tract dataset is empty or invalid.");
  tractData=data;const values=data.features.map(d=>+d.properties.mammography_pct).filter(Number.isFinite).sort(d3.ascending);
  if(!values.length)throw new Error("No valid mammography estimates were found.");
  const classes=makeClasses(values);renderSummary(values,data.features);renderMap(data,classes);renderLegend(classes);renderHistogram(values);renderLowest(data.features);renderInterpretation(values,data.features);document.querySelector("#loading").remove();
}).catch(error=>{const loading=document.querySelector("#loading");loading.textContent=`Unable to load dashboard data: ${error.message}. Use a local web server rather than opening index.html directly.`;loading.classList.add("error")});

function makeClasses(values){const scale=d3.scaleQuantile().domain(values).range(COLORS);return{scale,thresholds:scale.quantiles()}}
function renderSummary(values,features){document.querySelector("#tract-count").textContent=d3.format(",")(features.length);document.querySelector("#median-rate").textContent=formatPct(d3.median(values));document.querySelector("#rate-range").textContent=`${formatPct(d3.min(values))}–${formatPct(d3.max(values))}`}
function renderMap(data,classes){
  const expression=["step",["get","mammography_pct"],COLORS[0]];classes.thresholds.forEach((threshold,index)=>expression.push(threshold,COLORS[index+1]));
  map=new maplibregl.Map({container:"map",style:"https://tiles.openfreemap.org/styles/positron",center:[-121.92,37.31],zoom:8.55,minZoom:7.5,maxZoom:14,attributionControl:false});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");
  map.on("load",()=>{map.addSource("tracts",{type:"geojson",data,promoteId:"GEOID"});map.addLayer({id:"tract-fill",type:"fill",source:"tracts",paint:{"fill-color":expression,"fill-opacity":.78}});map.addLayer({id:"tract-outline",type:"line",source:"tracts",paint:{"line-color":["case",["boolean",["feature-state","selected"],false],"#d94841","#fff"],"line-width":["case",["boolean",["feature-state","selected"],false],2.5,.55],"line-opacity":.95}});fitToData(data);
    let selectedId=null;const select=feature=>{if(selectedId!==null)map.setFeatureState({source:"tracts",id:selectedId},{selected:false});selectedId=feature.properties.GEOID;map.setFeatureState({source:"tracts",id:selectedId},{selected:true});showTract(feature.properties)};
    map.on("mousemove","tract-fill",event=>{map.getCanvas().style.cursor="pointer";showTract(event.features[0].properties)});map.on("mouseleave","tract-fill",()=>{map.getCanvas().style.cursor="";if(selectedId!==null){const feature=data.features.find(d=>d.properties.GEOID===selectedId);showTract(feature.properties)}});map.on("click","tract-fill",event=>select(event.features[0]));
  });
}
function fitToData(data){const bounds=new maplibregl.LngLatBounds();const visit=coordinates=>typeof coordinates[0]==="number"?bounds.extend(coordinates):coordinates.forEach(visit);data.features.forEach(feature=>visit(feature.geometry.coordinates));map.fitBounds(bounds,{padding:32,duration:0})}
function showTract(p){document.querySelector("#tract-detail").innerHTML=`<span>Selected tract</span><h3>${p.NAME}</h3><dl><div><dt>GEOID</dt><dd>${p.GEOID}</dd></div><div><dt>Reported use</dt><dd>${formatPct(+p.mammography_pct)}</dd></div><div><dt>95% confidence interval</dt><dd>${p.mammography_ci}</dd></div></dl>`}
function renderLegend({scale}){const rows=scale.range().map(color=>{const[lo,hi]=scale.invertExtent(color);const label=lo==null?`< ${formatPct(hi)}`:hi==null?`≥ ${formatPct(lo)}`:`${formatPct(lo)}–${formatPct(hi)}`;return`<li><i style="background:${color}"></i><span>${label}</span></li>`}).join("");document.querySelector("#map-legend").innerHTML=`<strong>Reported mammography use</strong><ul>${rows}</ul><small>Quantile classes · % of women 50–74</small>`}
function chartFrame(selector,height,margins){const element=document.querySelector(selector);element.innerHTML="";const width=Math.max(300,element.clientWidth);const svg=d3.select(element).append("svg").attr("viewBox",`0 0 ${width} ${height}`).attr("role","img");return{svg,width,height,innerWidth:width-margins.left-margins.right,innerHeight:height-margins.top-margins.bottom,margins}}
function renderHistogram(values){const f=chartFrame("#histogram",320,{top:18,right:18,bottom:48,left:46}),x=d3.scaleLinear().domain(d3.extent(values)).nice().range([0,f.innerWidth]),bins=d3.bin().domain(x.domain()).thresholds(x.ticks(12))(values),y=d3.scaleLinear().domain([0,d3.max(bins,d=>d.length)]).nice().range([f.innerHeight,0]),g=f.svg.append("g").attr("transform",`translate(${f.margins.left},${f.margins.top})`);g.selectAll("rect").data(bins).join("rect").attr("x",d=>x(d.x0)+1).attr("y",d=>y(d.length)).attr("width",d=>Math.max(0,x(d.x1)-x(d.x0)-2)).attr("height",d=>f.innerHeight-y(d.length)).attr("fill","#3182bd").append("title").text(d=>`${formatPct(d.x0)} to ${formatPct(d.x1)}: ${d.length} tracts`);g.append("g").attr("transform",`translate(0,${f.innerHeight})`).call(d3.axisBottom(x).ticks(6).tickFormat(d=>`${d}%`));g.append("g").call(d3.axisLeft(y).ticks(5));g.append("text").attr("class","axis-label").attr("x",f.innerWidth/2).attr("y",f.innerHeight+42).attr("text-anchor","middle").text("Reported mammography use");g.append("text").attr("class","axis-label").attr("transform","rotate(-90)").attr("x",-f.innerHeight/2).attr("y",-36).attr("text-anchor","middle").text("Number of tracts")}
function renderLowest(features){const data=[...features].sort((a,b)=>d3.ascending(+a.properties.mammography_pct,+b.properties.mammography_pct)||d3.ascending(a.properties.GEOID,b.properties.GEOID)).slice(0,10),f=chartFrame("#lowest-chart",390,{top:10,right:48,bottom:42,left:118}),max=d3.max(data,d=>+d.properties.mammography_pct),min=d3.min(data,d=>+d.properties.mammography_pct),x=d3.scaleLinear().domain([Math.max(0,Math.floor(min-3)),Math.ceil(max+1)]).range([0,f.innerWidth]),y=d3.scaleBand().domain(data.map(d=>d.properties.GEOID)).range([0,f.innerHeight]).padding(.22),g=f.svg.append("g").attr("transform",`translate(${f.margins.left},${f.margins.top})`);g.selectAll("rect").data(data).join("rect").attr("x",x(x.domain()[0])).attr("y",d=>y(d.properties.GEOID)).attr("width",d=>x(+d.properties.mammography_pct)-x(x.domain()[0])).attr("height",y.bandwidth()).attr("fill","#d95f59").append("title").text(d=>`${d.properties.NAME}: ${formatPct(+d.properties.mammography_pct)}`);g.selectAll(".bar-value").data(data).join("text").attr("class","bar-value").attr("x",d=>x(+d.properties.mammography_pct)+5).attr("y",d=>y(d.properties.GEOID)+y.bandwidth()/2).attr("dy",".35em").text(d=>formatPct(+d.properties.mammography_pct));g.append("g").call(d3.axisLeft(y).tickFormat(id=>`Tract ${data.find(d=>d.properties.GEOID===id).properties.BASENAME}`));g.append("g").attr("transform",`translate(0,${f.innerHeight})`).call(d3.axisBottom(x).ticks(5).tickFormat(d=>`${d}%`))}
function renderInterpretation(values,features){const median=d3.median(values),min=d3.min(values),max=d3.max(values),sorted=[...features].sort((a,b)=>d3.ascending(+a.properties.mammography_pct,+b.properties.mammography_pct)),lowest=sorted[0].properties,highest=sorted.at(-1).properties;document.querySelector("#interpretation-copy").textContent=`Across ${features.length} tracts, the unweighted median estimate is ${formatPct(median)}. Estimates span ${formatPct(min)} in ${lowest.NAME} to ${formatPct(max)} in ${highest.NAME}, a ${formatPct(max-min)} percentage-point spread. The map and charts show geographic variation, but overlapping confidence intervals and the modeled nature of PLACES estimates mean small tract differences should be interpreted cautiously.`}
let resizeTimer;window.addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!tractData)return;const values=tractData.features.map(d=>+d.properties.mammography_pct).filter(Number.isFinite);renderHistogram(values);renderLowest(tractData.features);if(map)map.resize()},160)});
